package dankcompiler.errors;

public enum CompileErrorCode {
    LEXEM_UNKNOWN,
    MISMATCH,
    TOKEN_MISMATCH,
    TOKEN_UNEXPECTED,
    ID_UNEXPECTED,
    VAR_UNDEFINED,
    VAR_REDEFINITION,
    OPERATOR_INVALID,
    TYPE_EXPR_INCOMPATIBILITY
}
